"""update tasks table

Revision ID: 861d4ee65c87
Revises: 32cc6ceab06f
Create Date: 2025-07-28 08:02:35.117153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861d4ee65c87'
down_revision: Union[str, Sequence[str], None] = '32cc6ceab06f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column(
        'description', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column(
        'due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(
        timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_index(op.f('ix_tasks_task'), table_name='tasks')
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.drop_column('tasks', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.create_index(op.f('ix_tasks_task'), 'tasks', ['task'], unique=False)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
