"""sync_with_current_db_state

Revision ID: 8b5a05156045
Revises: 03746358d906
Create Date: 2025-08-22 23:54:48.647288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b5a05156045'
down_revision: Union[str, Sequence[str], None] = '03746358d906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_email_configs_id'), table_name='job_email_configs')
    op.drop_index(op.f('ix_job_email_configs_job_id'), table_name='job_email_configs')
    op.drop_table('job_email_configs')
    op.drop_constraint(op.f('uq_job_executions_execution_id'), 'job_executions', type_='unique')
    op.alter_column('task_notes', 'analysis_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('idx_tasks_is_archived'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tasks_is_archived'), 'tasks', ['is_archived'], unique=False)
    op.alter_column('task_notes', 'analysis_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(op.f('uq_job_executions_execution_id'), 'job_executions', ['execution_id'], postgresql_nulls_not_distinct=False)
    op.create_table('job_email_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('recipient', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('send_empty_reports', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('html_format', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('retry_failed_sends', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('job_email_configs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_email_configs_pkey')),
    sa.UniqueConstraint('job_id', 'user_id', name=op.f('unique_job_user_email_config'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_job_email_configs_job_id'), 'job_email_configs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_email_configs_id'), 'job_email_configs', ['id'], unique=False)
    # ### end Alembic commands ###
